// <auto-generated />
namespace Fitnessz.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class kliensberlet1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kliensberlet1));
        
        string IMigrationMetadata.Id
        {
            get { return "201905131413344_kliensberlet1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
